### ISSUE TITLE
CORS problems with Rack-cors gem

### ISSUE THREAD

**Issue by publicidadeba** [cyu/rack-cors#200] opened 2020-01-18 01:03 UTC
Having a hard time with permission. 
It works when I try to make a request to URLs(pages) and Ids from the same website, but when I tried to do the same with an external URL it didn´t work.

https://stackoverflow.com/questions/59796296/cors-problems-with-rack-cors-gem

**Comment by cyu** [comment] 2020-04-09 16:06
Closing this as the link no longer works.  Please re-open with more information if the problem is still occurring.

**Closed by cyu** 2020-04-09 16:06 UTC
