### ISSUE TITLE
CORS With database

### ISSUE THREAD

**Issue by puneetgaurr** [cyu/rack-cors#151] opened 2017-10-19 01:51 UTC
I am adding CORS validation in application.rb filw where domain names are given in Environment variable but I want to keep all domain in database table and validate these domain during CORS validation. I am unable to read database table in application.rb file. Could you please help me how I can implement this. Please find the below summary of this requirement.

1. Add domain name in Database table
2. Application will validate Domain whether requested domain is already existing in database or not , it would be first step because if domain is not registered in DB then won't allow
Thanks for your help. 

please note, i don't want to restart the server.

**Comment by cyu** [comment] 2017-10-19 02:35
@puneetgaurr You'll want to specify origins with a proc and in that proc run a DB query to do a database lookup.  With Rails or any framework you use, the database connection will be created & disposed of downstream of the CORS middleware, so you would have to deal with the db connection yourself.  Also, you'll probably want to cache that query in memory so you're not hitting the database with every request.  Or better yet, fetch that information from Redis instead.

**Comment by puneetgaurr** [comment] 2017-10-19 07:51
Thanks Cyu. Is it possible to share some sample code for the same? We have written code for the same but we need to restart Heroku server whenever add any new origin in database.

**Comment by puneetgaurr** [comment] 2017-10-19 12:53
Hi Cyu,

We have added code to read whitelisted domain from database and able to restrict but whenever we are adding new domain in database then seems to me need to restart Heroku Server which would be causing data loss issue if any job running behind.

Regards,
Puneet Gaur

**Comment by puneetgaurr** [comment] 2017-10-19 12:55
Could you please let me know how I can avoid Heroku Restart here.

**Comment by cyu** [comment] 2017-10-19 13:03
Without seeing any code, there could be many reasons why this is happening outside of Rack::Cors.  If you're doing the restrictions within a proc, it should run on ever request and work as stated.

I recommend checking the following:

1) Make sure how you're testing is valid
2) Is the way you're querying the database causing the results to be cached?
3) Is there some upstream process caching the results?
4) Is the browser caching the results?
5) Can you produce a test case that reproduces this issue?  (the test case shouldn't need to use a database, just cycle through origins for each request).

**Comment by rajcybage** [comment] 2017-10-21 15:15
Hi CYU;

I can give one example of our code as per doc we set up our application.rb


 config.middleware.insert_before 0, "Rack::Cors" do
      allow do
        origins MyDomain.pluck(:links)

```

Now here we are fetch all the links(MyDomain.pluck(:links)) which will allow 

Now if any one update one links in DB table it is not able to pick up that updated links . AS it is in application.rb

So Every time we need to restart the heroku.

Please let us know if we are doing anything miss here.

Thanks & Best Regards
Rajarshi

**Comment by hyeomans** [comment] 2018-02-25 01:34
Hey Rajarshi,

I know I'm late to the party but I was thinking you need to pass a lambda which will have reference to the database connection. As CYU mentioned you still need to handle caching of domains.

**Comment by cyu** [comment] 2020-05-07 15:47
I'm closing this issue because there hasn't been any activity on this issue in a while.

**Closed** 2020-05-07 15:47 UTC

**Comment by prvinuch** [comment] 2021-08-02 07:27
Hi Tehcies, 
I've similar problem as this issue, since there has been quite a time, I hope @puneetgaurr got answer to your query.
would you like to share if you got one.
