### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by mohdsameer** [cyu/rack-cors#143] opened 2017-07-30 18:11 UTC
Hi

I am creating a JS widget in rails and using the custom fonts in the widget css using @font-face.
but i am getting this error when i put my widget on another site
`Access to Font at 'http://localhost:3000/assets/AvenirNextCyr/AvenirNextCyr-MediumItalic-774c88c40255e677b903e1719165c78eeb78d6c80902cf79c60bd79e3fc73542.otf' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested `resource. Origin 'null' is therefore not allowed access.
Here is my configuration in `application.rb`
  ```
config.middleware.insert_before ActionDispatch::Static, Rack::Cors do
      allow do
        origins '*'
        resource '*', headers: :any, methods: [:get, :post, :options]
      end
    end
```

Please provide me a solution.
Thanks in advance

**Comment by devtoro** [comment] 2017-08-09 10:08
I have similar issue after I updated to version 1.0.1. The version I was using before that was 0.4.1.
I have an ember js application and the error I got was:

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.`

I rolled back to 0.4.1 and everything is working again as expected.  
Hope this helps to resolve this issue.

**Comment by cyu** [comment] 2017-08-09 15:02
@mohdsameer is this your problem? https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin

**Comment by cyu** [comment] 2017-08-09 15:04
@devtoro can you provide more details as to why 1.0.1 isn't working for you?  There's a lot of good updates in 1.0.1, and if there are any regressions I want to make sure I address them.

**Comment by jezstarr** [comment] 2017-08-22 15:51
I'm having a similar problem. We just upgraded to 1.0.1 (and were using 0.4.1) for our Rails-Angular app and are now getting this error in the Angular app:

`Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by cyu** [comment] 2017-08-23 01:53
@jezstarr trying setting `credentials: true` option for the resource you're trying to access.  This default for this value is now `false`.  Also, you can't set `credentials: true` option with wildcard origins anymore for security reasons.

**Comment by jezstarr** [comment] 2017-08-23 14:24
Thanks @cyu we did eventually figure that out. Given that this was a breaking change, some kind of heads up in the release or in the readme would have been helpful.

**Comment by emilioforrer** [comment] 2017-09-17 02:31
How about a cordova/phonegap application? when I upgraded the gem the cordova apps got broken, because of wildcard in origin. I had to downgrade the gem to make it work.

**Comment by devtoro** [comment] 2018-01-25 10:02
@cyu Actually I am using 1.0.2. I still don't quite get it, as I have configured everything and when I hit [options] route_path with postman, I get the 404 Routing Error. ( e.g. ActionController::RoutingError (No route matches [OPTIONS] "/users/sign_in"): ).

If I try to login in my Ember app, I get the following error:
`Failed to load http://localhost:3000/users/sign_in: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.`

In production I am using version 0.4.1 and for now it is OK. I could set up CORS with nginx directly, but it is easier to configure it in the application level.

What other information would you like me to share?

**Comment by cyu** [comment] 2018-01-25 14:09
@devtoro What does your Rack::CORS configuration look like?

In 1.0.2, preflight requests should be handled by the middleware and not make it to the Rails router - unless there isn't an origin/resource rule for that route.

**Comment by krue-doug** [comment] 2018-08-15 14:54
I am having issues with iOS Safari. I am using my iPhone to hit my local server on my computer and network. It works fine on my computer, and even in production. 

This is how my CORs setup looks like:

```ruby
    # Cors
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins (Rails.application.config.allowed_cors_origins || '').split(',')
        resource '*', headers: :any, methods: [:get, :put, :post, :options]
      end
    end
```

When I attempt to login which makes a POST to request to my Rails server from my React app, it just hangs and spins forever on the preflight. Here is a copy of the request from Safari's network tab when debugging my iOS Safari:

```bash
curl 'http://localhost:3001/oauth/token.json' \
-XOPTIONS \
-H 'Access-Control-Request-Headers: authorization,content-type' \
-H 'Origin: http://192.168.1.4:3000' \
-H 'Accept: */*' \
-H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1' \
-H 'Referer: http://192.168.1.4:3000/login' \
-H 'Access-Control-Request-Method: POST'```

**Comment by cyu** [comment] 2018-08-15 14:59
@krue-doug My guess is that the issue is with `Rails.application.config.allowed_cors_origins`.  Have you removed that to see what happens?

**Comment by krue-doug** [comment] 2018-08-15 15:00
@cyu Ahh I should have showed you that. It's just a string in my environmental variables like this for local: `"localhost:3000,192.168.1.4:3000"`

**Comment by krue-doug** [comment] 2018-08-15 15:03
@cyu I just removed it and tested it with:
```ruby
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins "localhost:3000", "192.168.1.4:3000"
        resource '*', headers: :any, methods: [:get, :put, :post, :options]
      end
    end
```
It works in Chrome on my Mac, but not in my iOS Safari. Here is how the Chrome's response headers look:
```bash
curl 'http://localhost:3001/oauth/token.json' -X OPTIONS -H 'Pragma: no-cache' -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,ja;q=0.8' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization,content-type' --compressed```

**Comment by girichandu143** [comment] 2018-08-31 06:55
simple just create filter

public class CORSFilter implements Filter {
     public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException
 {      
  System.out.println("Filtering on...........................................................");     
   HttpServletResponse response = (HttpServletResponse) res;       
 response.setHeader("Access-Control-Allow-Origin", "*");       
 response.setHeader("Access-Control-Allow-Methods", "POST, GET, PUT, OPTIONS, DELETE");      
  response.setHeader("Access-Control-Max-Age", "3600");   
     response.setHeader("Access-Control-Allow-Headers", "X-requested-with, Content-Type");   
     chain.doFilter(req, res);    }    
 public void init(FilterConfig filterConfig) {}   
  public void destroy() {}

 }
--

**Comment by OswlC001** [comment] 2018-10-06 02:43
> simple just create filter
> 
> public class CORSFilter implements Filter {
>      public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException
> {      
>   System.out.println("Filtering on...........................................................");     
>    HttpServletResponse response = (HttpServletResponse) res;       
>  response.setHeader("Access-Control-Allow-Origin", "*");       
>  response.setHeader("Access-Control-Allow-Methods", "POST, GET, PUT, OPTIONS, DELETE");      
>   response.setHeader("Access-Control-Max-Age", "3600");   
>      response.setHeader("Access-Control-Allow-Headers", "X-requested-with, Content-Type");   
>      chain.doFilter(req, res);    }    
>  public void init(FilterConfig filterConfig) {}   
>   public void destroy() {}
> 
> ##  }

**Comment by rmcsharry** [comment] 2018-10-14 23:12
@cyu You said:

> My guess is that the issue is with `Rails.application.config.allowed_cors_origins.` Have you removed that to see what happens?

I just upgraded from 0.4.1 to 1.02 and this was the problem.

In development.rb I had:

`config = ENV["ALLOWED_CORS_ORIGINS"]`

I also tried doing the same with secrets.yml (ie. origins Rails.application.config.secrets.allowed_cors_origins, which was also reading from ENV var).

 **In both cases Origins does not get set.** 

Origins is an empty string when used like this:

`origins Rails.application.config.allowed_cors_origins.to_s`

and throws a startup cannot be nil error when used like this:

`origins Rails.application.config.allowed_cors_origins`

A shame that I cannot use env vars any longer to pass such values to origins. Is there a specific reason that was removed?

**Comment by cyu** [comment] 2018-10-15 03:05
@rmcsharry To be honest, I'm not sure what my thinking was when I made that comment.

Having said that, there's nothing in the middleware that would prevent this from working.  This doesn't seem to be anything to do with rack-cors, but with Rails configuration order (meaning `development.rb` is executed after the middleware is loaded).  Have you added print statements to confirm the config is getting setting before the middleware is configured?

**Comment by rmcsharry** [comment] 2018-10-15 19:47
@cyu fair point on your thinking but whatever you were thinking, you made me think - I would never have posted otherwise :)  

So also "having said that" I wondered about the same thing you did...the loading of configuration order. 

What I found odd is that this worked:

**\environments\development.rb**
```
Rails.application.configure do
  config.allowed_cors_origins = 'http://localhost:4200'
...
end

```
This made me realise that `.dotenv` was loading after the middleware and hence that is why the ENV VAR was nil. I found the answer [here](https://github.com/bkeepers/dotenv#note-on-load-order).

So a BIG thank you - you put me on the right track!

**Comment by ShrJoshi28** [comment] 2019-01-30 07:18
I have error- Access to XMLHttpRequest at 'https://4kd2hi3ere.execute-api.us-east-1.amazonaws.com/default/myfirstvuecode' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
how to slove this problem using vue js and aws lambda function.

**Comment by gadni** [comment] 2019-02-08 11:21
@ShrJoshi28 - you need to return some CORS headers from your API Gateway. Go over reading the following discussion:
https://stackoverflow.com/questions/35190615/api-gateway-cors-no-access-control-allow-origin-header

**Comment by cyu** [comment] 2019-08-08 13:54
Closing - the title of the issue is basically equivalent to "CORS is not working", which basically had made this issue a mismatch of different issues.  If you're still having problems, please open an issue with more specifics.

**Closed by cyu** 2019-08-08 13:54 UTC
